config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#welcome'
  get '/home' => 'pages#home'

  # Session routes:

  # login form
  get '/login' => 'session#new'

  # form submits here, do authentication and create session, redirect or show form with errors
  post '/login' => 'session#create'

  # logout, ie delete session for this user
  delete '/login' => 'session#destroy'

  # Users CRUD
  resources :users

  # FantasyTeams CRUD
  resources :fantasyteams

  # Players CRUD
  resources :players

  # Teams CRUD
  resources :teams

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fantasyteam.rb
class Fantasyteam < ApplicationRecord

  has_and_belongs_to_many :players
  belongs_to :user, optional: true
  has_many :teams, through: 'players'

  has_many :home_match_relationships, class_name: 'Match', foreign_key: 'home_id', dependent: :destroy
  has_many :visitor_match_relationships, class_name: 'Match', foreign_key: 'visitor_id', dependent: :destroy

  has_many :home_matches, through: 'home_match_relationships', source:'visitor_team'
  has_many :visitor_matches, through: 'visitor_match_relationships', source: 'home_team'


end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_team, class_name: 'Fantasyteam'
  belongs_to :visitor_team, class_name: 'Fantasyteam'
end

app/models/player.rb
class Player < ApplicationRecord
  has_and_belongs_to_many :fantasyteams
  belongs_to :team, optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
end

app/models/user.rb
class User < ApplicationRecord
  has_many :fantasyteams

  has_secure_password

  validates :name, length: { minimum: 2 }

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :fetch_user

    def fetch_user
      if session[:user_id].present?
        @current_user = User.find_by id: session[:user_id]
      end # if
      unless @current_user.present?
        session[:user_id] = nil
      end # unless
    end # fetch_user

    def check_if_logged_in
      redirect_to login_path unless @current_user.present?
    end


  end # ApplicationController

app/controllers/fantasyteams_controller.rb
class FantasyteamsController < ApplicationController
  # Let's decide that all the fantasyteam-modifying pages require a user
  # to be logged in (because fantasyteams belong_to users)
  # BUT you don't have to be logged in to see the index of fantasyteams
  # or to view the details of specific fantasyteams
  before_action :check_if_logged_in, except: [:index, :show]

  def new
    @fantasyteam = Fantasyteam.new
    @players = Player.all
  end # new

  def create
    # raise 'hell'
    # Create fantasyteam, and associate it with the logged-in user
    @fantasyteam = Fantasyteam.new fantasyteam_params

    # Handle upload
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @fantasyteam.image = response['public_id']
    end

    @fantasyteam.user_id = @current_user.id
    @fantasyteam.save
    @fantasyteam.players << Player.find(params[:players])
    redirect_to fantasyteams_path
  end # create

  def index
    @fantasyteams = Fantasyteam.all
  end # index

  def show
    @fantasyteam = Fantasyteam.find params[:id] # from /fantasyteams/:id
  end # show

  def edit
    @fantasyteam = Fantasyteam.find params[:id]
    @players = Player.all


    # raise 'hell'

    redirect_to fantasyteams_path unless @fantasyteam.user_id == @current_user.id
  end

  def update
    @fantasyteam = Fantasyteam.find params[:id]
    if @fantasyteam.user != @current_user
      redirect_to fantasyteams_path
      return # leave the function early!! i.e. dont do the update below
    end


    @fantasyteam.players.clear
    @fantasyteam.players << Player.find(params[:players])

    @fantasyteam.update fantasyteam_params # actually perform the update using the strong params

    redirect_to fantasyteam_path(@fantasyteam) # you can leave off .id when you pass an object
  end

  def destroy
    Fantasyteam.destroy params[:id]
    redirect_to user_path(@current_user)
  end # destroy

  def fantasyteam_params
    params.require(:fantasyteam).permit(:name, :image)
  end # fantasyteam_params
end # FantasyteamsController

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :check_if_logged_in, only: [ :home ]

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.all
  end

  def show
    @player = Player.find params[:id]
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  # if Login successful create session
  def create
    user = User.find_by email: params[:email]
      if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path
      else
      flash[:error] = 'Invalid email or password'
      redirect_to login_path # show the login form again to correct errors
      end # login check

  end # create

  def destroy
    session[:user_id] = nil # This logs out the user
    redirect_to login_path # Go back to the logins
  end # destroy

end # SessionController

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new # the form_form helper needs '@user'
  end

  def create

    @user = User.create user_params

    # Handle upload
    if params[:file].present?
      # actually forward uploaded file on to Cloudinary server
      response = Cloudinary::Uploader.upload params[:file]
      @user.image = response['public_id']
      @user.save
    end

    # Check whether the above create was successful (ie created a
    # row in the users table ie the object has an id)
    # or if it failed due to a data validation error
    if @user.persisted?
      session[:user_id] = @user.id # log in the newly created account automatically!
      redirect_to root_path
    else
      render :new # show the form again directly, no redirect keeps all the data on the page
    end #if
  end # create

  def show
    @user = User.find params[:id]
  end

  private
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fantasyteams_helper.rb
module FantasyteamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fantasyteams/edit.html.erb
<h2>Edit Your Fantasy Team</h2>

<%= form_for @fantasyteam do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :image, 'Image URL' %>
  <%= f.text_field :image %>
  <br>
  <ul style="list-style-type:none;">
    <% @players.each do |player| %>
      <div class="edit_fantasyteam">
        <li>

          <%= label_tag do %>
          <%= check_box_tag 'players[]', player.id, @fantasyteam.players.include?(player) %>
          <%= cl_image_tag player.image %>
          <% end %>

        </li>
      </div>
    <% end %>
  </ul>

<%= f.submit "Edit Fantasy Team" %>

<% end %>

app/views/fantasyteams/index.html.erb
<h2>All Fantasy Teams</h2>

<ul style="list-style-type:none;">
  <% @fantasyteams.each do |f| %>
  <li>
    <%= link_to f.name, fantasyteam_path(f.id) %>
    - (Manager <%= f.user.name %>)
  </li>
  <% end %>
</ul>

app/views/fantasyteams/new.html.erb
<h2>Create Your Fantasy Team</h2>

<%= form_for @fantasyteam, html: {multipart: true} do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :image, 'Team Logo' %>
  <%= f.cl_image_upload :image %>
  <br>

<ul style="list-style-type:none;">
  <% @players.each do |player| %>
    <div class="new_fantasyteam">
      <li>
        <%= label_tag do %>
          <%= check_box_tag 'players[]', player.id %>
          <%= cl_image_tag player.image %>
        <% end %>
      </li>
    </div>
  <% end %>
</ul>

<%= f.submit "Create Fantasy Team" %>

<% end %>

app/views/fantasyteams/show.html.erb
<h2>
  <%= @fantasyteam.name %>
</h2>
<div class="fantasyteam_image">
  <%= cl_image_tag @fantasyteam.image, :width=>150, :height=>150, :gravity=>"faces", :crop=>"fill", :radius=>"max" %>
</div>
<% if @fantasyteam.user_id == @current_user.id %>
  <%= link_to 'Edit Your Fantasy Team', edit_fantasyteam_path(@fantasyteam) %>
  <%= link_to 'Delete Your Fantasy Team', fantasyteam_path(@fantasyteam), method: 'delete' %>
<% end %>
<ul style="list-style-type:none;">
  <% @fantasyteam.players.each do |p| %>
  <div class="fantasyteam">
    <li>
      <a href="<%= player_path(p.id) %>">
        <%= cl_image_tag p.image, alt: p.name%>
      </a>
    </li>
  </div>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fantasy Football</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="wrapper">

      <% if @current_user.present? %>
      <div class="topnav">
        <%= link_to 'Home', home_path %>

        <div class="subnav">
          <button class="subnavbtn">Dashboard <i class="fa fa-caret-down"></i></button>
          <div class="subnav-content">
            <%= link_to 'Manager-Mode', user_path(@current_user) %>
            <%= link_to 'Teams', teams_path %>
            <%= link_to 'Players', players_path %>
            <%= link_to 'Fantasy Teams', fantasyteams_path %>
          </div>
        </div>

        <div class="topnav-right">
          <%= link_to 'Logout', login_path, method: 'delete' %>
        </div>
        <div class="hello">
          Hello, <%= @current_user.name %>
        </div>
      </div>

      <% else %>

      <div class="topnav">
        <%= link_to 'Home', home_path %>
        <div class="topnav-right">
          <%= link_to 'Login', login_path %>
          <%= link_to 'Sign Up', new_user_path %>
        </div>
      </div>

      <% end %>

      <%= yield %>
      <div class="push"></div>
    </div>
    <footer class="footer">
      &copy; SB Productions
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<h2>to</h2>
<h1>Fantasy Football</h1>
<h2>Create your fantasy team and compete</h2>

app/views/pages/welcome.html.erb
<h1>Welcome</h1>
<h2>to</h2>
<h1>Fantasy Football</h1>
<h2>Create your fantasy team and compete</h2>

app/views/players/index.html.erb
<h3>Players</h3>

<ul style="list-style-type:none;">
      <% @players.each do |p| %>
      <div class="players">
        <li>
          <a href="<%= player_path(p.id) %>">
            <%= cl_image_tag p.image, alt: p.name%>
          </a>
        </li>
      </div>
      <% end %>
</ul>

app/views/players/show.html.erb
<h2><%= @player.name %></h2>

<%= cl_image_tag @player.image, alt: @player.name%>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h2>Login</h2>

    <% if flash[:error] %>
    <!-- print out any error message from the controller -->
    <br>
    <strong>
      <%= flash[:error] %>
    </strong>
    <br>
    <br>
    <% end %>
    <!-- we are not interacting with a model object -->
    <div class="form-inline">

      <%= form_tag login_path, {class: 'login'} do %>

      <%= label_tag :email %>
      <%= email_field_tag :email%>
      <br>

      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <br>

      <%= submit_tag 'Login'%>
      <% end %>
    </div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h2>Create an Account</h2>

<% if @user.errors.full_messages.any? %> <!-- active record provides errors.full_messages automatically -->
  <ul>
    <% @user.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
<% end %>
<!-- form_with is the newest way of doing forms in rails, both model-related and non-model -->
<%= form_for @user, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :image, 'User Avatar' %>
  <%= f.cl_image_upload :image %>
  <br>

  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.submit 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<%= cl_image_tag @user.image, :width=>150, :height=>150, :gravity=>"faces", :crop=>"fill", :radius=>"max" %>
<div class="container">
  <%= link_to 'Create New Fantasy Team', new_fantasyteam_path %>
</div>
<h3>Your Fantasy Teams</h3>


<% @current_user.fantasyteams.each do |t|  %>
  <%= link_to t.name, fantasyteam_path(t.id) %>
  <br>
<% end %>